name: Supabase Keep Alive

on:
  schedule:
    # This runs at 00:00 every Monday and Thursday
    - cron: '0 0 * * 1,4'
  workflow_dispatch: # This adds a "Run now" button in GitHub for testing

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Supabase
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/projects?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"